# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Calculate the Mord statistic
#'
#' @param item_no The item number
#' @param LCprob Item parameters
#' @param prior Class membership probabilities
#' @author Wenchao Ma, https://github.com/Wenchao-Ma/GDINA
#' @noRd
#'
Mord <- function(item_no, LCprob, prior) {
    .Call(`_dcm2_Mord`, item_no, LCprob, prior)
}

